CATEGORY_MAPPING = {
    'Aggressive Driving/Road Rage': 'Misc Human Errors',
    'Pavement Slippery': 'Environmental Factors',
    'Following Too Closely': 'Driver Inattention/Distraction',
    'Unspecified': 'Miscellaneous',
    'nan': 'Miscellaneous',
    'Passing Too Closely': 'Misc Human Errors',
    'Driver Inexperience': 'Misc Human Errors',
    'Passing or Lane Usage Improper': 'Misc Human Errors',
    'Turning Improperly': 'Misc Human Errors',
    'Unsafe Lane Changing': 'Misc Human Errors',
    'Unsafe Speed': 'Misc Human Errors',
    'Reaction to Uninvolved Vehicle': 'Misc Human Errors',
    'Steering Failure': 'Mechanical Issues',
    'Traffic Control Disregarded': 'Traffic Control Disregarded',
    'Other Vehicular': 'Misc Human Errors',
    'Driver Inattention/Distraction': 'Driver Inattention/Distraction',
    'Oversized Vehicle': 'Misc Human Errors',
    'Pedestrian/Bicyclist/Other Pedestrian Error/Confusion': 'Misc Human Errors',
    'Alcohol Involvement': 'Substance Influence',
    'View Obstructed/Limited': 'Misc Human Errors',
    'Failure to Yield Right-of-Way': 'Failure to Yield Right-of-Way',
    'Illnes': 'Miscellaneous',
    'Lost Consciousness': 'Misc Human Errors',
    'Brakes Defective': 'Mechanical Issues',
    'Backing Unsafely': 'Misc Human Errors',
    'Glare': 'Misc Human Errors',
    'Passenger Distraction': 'Misc Human Errors',
    'Fell Asleep': 'Misc Human Errors',
    'Obstruction/Debris': 'Environmental Factors',
    'Tinted Windows': 'Miscellaneous',
    'Animals Action': 'Environmental Factors',
    'Drugs (illegal)': 'Substance Influence',
    'Pavement Defective': 'Environmental Factors',
    'Other Lighting Defects': 'Environmental Factors',
    'Outside Car Distraction': 'Misc Human Errors',
    'Driverless/Runaway Vehicle': 'Misc Human Errors',
    'Tire Failure/Inadequate': 'Mechanical Issues',
    'Fatigued/Drowsy': 'Misc Human Errors',
    'Headlights Defective': 'Mechanical Issues',
    'Accelerator Defective': 'Mechanical Issues',
    'Failure to Keep Right': 'Misc Human Errors',
    'Physical Disability': 'Misc Human Errors',
    'Eating or Drinking': 'Misc Human Errors',
    'Cell Phone (hands-free)': 'Misc Human Errors',
    'Lane Marking Improper/Inadequate': 'Misc Human Errors',
    'Cell Phone (hand-Held)': 'Misc Human Errors',
    'Using On Board Navigation Device': 'Misc Human Errors',
    'Other Electronic Device': 'Misc Human Errors',
    'Traffic Control Device Improper/Non-Working': 'Miscellaneous',
    'Tow Hitch Defective': 'Mechanical Issues',
    'Windshield Inadequate': 'Mechanical Issues',
    'Vehicle Vandalism': 'Miscellaneous',
    'Prescription Medication': 'Substance Influence',
    'Shoulders Defective/Improper': 'Environmental Factors',
    'Listening/Using Headphones': 'Misc Human Errors',
    'Texting': 'Misc Human Errors',
    '80': 'Miscellaneous',
    'Reaction to Other Uninvolved Vehicle': 'Misc Human Errors',
    '1': 'Miscellaneous',
    'Drugs (Illegal)': 'Substance Influence',
    'Illness': 'Miscellaneous',
    'Cell Phone (hand-held)': 'Misc Human Errors'
}

COLS_TO_REMOVE = ['LATITUDE', 'LONGITUDE', 'LOCATION', 'CROSS STREET NAME', 'ON STREET NAME', 'OFF STREET NAME',  'CONTRIBUTING FACTOR VEHICLE 2', 'CONTRIBUTING FACTOR VEHICLE 3',
       'CONTRIBUTING FACTOR VEHICLE 4', 'CONTRIBUTING FACTOR VEHICLE 5', 'VEHICLE TYPE CODE 1', 'VEHICLE TYPE CODE 2',
       'VEHICLE TYPE CODE 3', 'VEHICLE TYPE CODE 4',
       'VEHICLE TYPE CODE 5', 'ZIP CODE', 'COLLISION_ID']

MONTH_TO_WORD = {
    1: 'January',
    2: 'February',
    3: 'March',
    4: 'April',
    5: 'May',
    6: 'June',
    7: 'July',
    8: 'August',
    9: 'September',
    10: 'October',
    11: 'November',
    12: 'December'
}

INJURED_KILLED_COLS = ['NUMBER OF PEDESTRIANS INJURED',
                       'NUMBER OF PEDESTRIANS KILLED', 'NUMBER OF CYCLIST INJURED',
                       'NUMBER OF CYCLIST KILLED', 'NUMBER OF MOTORIST INJURED',
                       'NUMBER OF MOTORIST KILLED']